### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by aubryssme** [Xientraa/The-Sims-Resource-Downloader#13]
Its saying
C:\Users\chadw>python src/main.py
python: can't open file 'C:\Users\chadw\src\main.py': [Errno 2] No such file or directory
and its not working. Please help.

**Comment by Xientraa** [comment]
My apologies, I just saw your other comment.
You seem to be in the wrong directory, you can type `cd C:\Path\To\Folder` to manually change directories.
Replace C:\Path\To\Folder with the path to the folder which contains the src folder, after that you can run `python src/main.py`.

**Comment by aubryssme** [comment]
Okay Thank you!
