### ISSUE TITLE
Downloading Error

### ISSUE THREAD

**Issue by MLGMagicHoodini** [Xientraa/The-Sims-Resource-Downloader#15]
[ERROR] ('https://www.thesimsresource.com/ajax.php?c=downloads&a=getdownloadurl&ajax=1&itemid=1603472&mid=0&lk=0', <RequestsCookieJar[Cookie(version=0, name='tsrdlsession', value='tsrdlsession6536d5f526a05', port=None, port_specified=False, domain='', domain_specified=False, domain_initial_dot=False, path='/', path_specified=True, secure=False, expires=None, discard=True, comment=None, comment_url=None, rest={'HttpOnly': None}, rfc2109=False), Cookie(version=0, name='tsrdlticket', value='tsr6536f61b5848a0.23484815', port=None, port_specified=False, domain='.thesimsresource.com', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=None, discard=True, comment=None, comment_url=None, rest={}, rfc2109=False), Cookie(version=0, name='tsrdlsession', value='tsrdlsession6536f61cca908', port=None, port_specified=False, domain='.thesimsresource.com', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=None, discard=True, comment=None, comment_url=None, rest={}, rfc2109=False)]>)

**Comment by MLGMagicHoodini** [comment]
Okay, so after restarting the program it seems to work? Is there some kind of timeout system or something?

**Comment by sadsmallcoconut** [comment]
I'm able to download most stuff but I've had to stop downloading VIP stuff cause I kept getting [ERROR] Invalid URL 'None': No scheme supplied. Perhaps you meant http://None?

**Comment by sadsmallcoconut** [comment]
I'm able to download most stuff but I've had to stop downloading VIP stuff cause I kept getting [ERROR] Invalid URL 'None': No scheme supplied. Perhaps you meant http://None?
