### ISSUE TITLE
CAPTCHA not accepted even though correct multiple times

### ISSUE THREAD

**Issue by D20Nypmh** [Xientraa/The-Sims-Resource-Downloader#16]
![image](https://github.com/Xientraa/The-Sims-Resource-Downloader/assets/141533375/15c7b172-fdb6-4b5c-8f7a-6fbed6e5fba9)

**Comment by DexMerx556** [comment]
Same issue for me. Any possible solutions?

**Comment by DexMerx556** [comment]
Working now. I turned on debug mode in config and seemed to fix it for me.

**Comment by D20Nypmh** [comment]
> Working now. I turned on debug mode in config and seemed to fix it for me.

awesome thank you! :)

**Comment by Xientraa** [comment]
Very strange issue, seems to be quite intermittent. I believe this may be an issue with the website itself, as I am having issues downloading custom content manually as well. I will keep an eye on this and will look for a workaround if this isn't a site issue.

**Comment by ThatIcyElf1** [comment]
are you aware if this is a website issue or a problem with the tool itself, thanks in advance

**Comment by D20Nypmh** [comment]
> Very strange issue, seems to be quite intermittent. I believe this may be an issue with the website itself, as I am having issues downloading custom content manually as well. I will keep an eye on this and will look for a workaround if this isn't a site issue.

Thanks for the fast response, haven't had the chance to try again yet but as soon as I do, I will update :)

**Comment by Xientraa** [comment]
They have seemed to have fixed their site, at least on my end. Though it does seem like they made a minor change to their captcha. Currently testing it out and if it works should hopefully have a bug fix released later today.

**Comment by Xientraa** [comment]
Should be fixed in the latest release.
https://github.com/Xientraa/The-Sims-Resource-Downloader/releases/tag/v0.4.2

**Comment by D20Nypmh** [comment]
> Should be fixed in the latest release. https://github.com/Xientraa/The-Sims-Resource-Downloader/releases/tag/v0.4.2

Working perfectly - Thank you so much!
