### ISSUE TITLE
Powershell says it downloaded the file I want, but it wont show up in the directory?

### ISSUE THREAD

**Issue by yesomg** [Xientraa/The-Sims-Resource-Downloader#18]
Everything seems to be working except that the file Powershell claims to have downloaded won't show up in the folder of my directory... Idk what I'm doing wrong
![image](https://github.com/Xientraa/The-Sims-Resource-Downloader/assets/101358052/6c686f0b-7156-4408-b10f-a864728114f1)
![image](https://github.com/Xientraa/The-Sims-Resource-Downloader/assets/101358052/8e31c08c-3bc3-4879-9f94-a29d761b37c3)
![image](https://github.com/Xientraa/The-Sims-Resource-Downloader/assets/101358052/e914a019-eb93-48dd-baf6-08d0cdb57754)

**Comment by Xientraa** [comment]
It seems you are editing the config.py file instead of the config.json file. Please undo any changes to the config.py file and redo them in the config.json file.

**Comment by yesomg** [comment]
> It seems you are editing the config.py file instead of the config.json file. Please undo any changes to the config.py file and redo them in the config.json file.
> 
> Also the content you downloaded, if the config is unchanged and following the Wiki should be downloaded to the root of the repo (the folder which contains: src, readme).

THANK YOU SO MUCH I FEEL SO DUMB NOW BUT IT WORKS FINALLY
