### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 2 column 28 (char 29)

### ISSUE THREAD

**Issue by RunningWithScisso** [Xientraa/The-Sims-Resource-Downloader#22]
hello after I created the enviroment, I got this error 

![Screenshot 2024-03-16 100253](https://github.com/Xientraa/The-Sims-Resource-Downloader/assets/163667527/aa75b05c-43fc-405a-b4e8-3fd1d484afd4)

**Comment by Xientraa** [comment]
Could you double-check your config.json file and add a comma at the end of line 2 then try running it again?
If the same issue occurs, could you also provide your config.json?

**Comment by RunningWithScisso** [comment]
OK, I will do that

**Comment by RunningWithScisso** [comment]
> Could you double-check your config.json file and add a comma at the end of line 2 then try running it again? If the same issue occurs, could you also provide your config.json?

fixed it, it turns out the issue was that I had accidentally added in an extra quotation mark when I was putting in the download directory which I was too tired to notice at the time.
