### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by OneThatNeverLearns** [Xientraa/The-Sims-Resource-Downloader#4]
So, i'm kinda retarded, and been trying to figure out how to use your tool for a while, managed to do the pip install, but doing the "Usage" step it gives this. i'm assuming it failed. if you could help. appreciate it

![Untitled](https://user-images.githubusercontent.com/58854809/236714920-55a05676-078d-4912-bdc5-f22af132e1f2.png)

**Comment by Xientraa** [comment]
Could you check your downloadPath in the config?
If your path contains singular backslashes, try doubling them up.

```sh
# Example of before
C:\some\path\to\directory

# Example of after
C:\\some\\path\\to\\directory
```

**Comment by OneThatNeverLearns** [comment]
Hey, thanks for replying. I followed your advice and it worked but it seems it got stuck in the "starting download" i let it run for 5 minutes and nothing changed 
![1](https://user-images.githubusercontent.com/58854809/236912661-14cc41dc-9d82-4633-b893-b52c211f9fe6.png)

And nothing showed up in the download directory either. 
![2](https://user-images.githubusercontent.com/58854809/236913074-d4ede368-cd10-46a5-aa69-3fcce994ef61.png)


I have noticed that the "TheSimsResource" site now has basically 2 downloads timers, first a 14 second one and then a 4 second one, i don't know if that changed affected your tool.

**Comment by Xientraa** [comment]
Tested it out on my end, and it works, I discovered it freezes up like that if the downloadPath does not exist.
Looking at your downloadPath you have a ./ before the directory.

Corrected config file:
```json
{
	"downloadDirectory": "D:\\Sims4Mods",
	"maxDownloads": 5
}
```

**Comment by OneThatNeverLearns** [comment]
I tested it, you where correct, the ./ was the issue. it downloaded now. Thank you. Very useful tool you have here. Keep up the great work and thank you for the help. have a nice day
