### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by annasayswho** [Xientraa/The-Sims-Resource-Downloader#9]
Hello, i'm super new at this and don't know a single thing of how to operate your tool, if it's not much bother, could you explain please? Or send me tutorials to learn by myself? Thank you in advance!

**Comment by Xientraa** [comment]
You'll want to install Python from https://www.python.org/ and when installing, make sure the option "Add python to environment variables" is checked.

After Python is installed, you'll want to download the latest release source code from [Latest (release)](https://github.com/Xientraa/The-Sims-Resource-Downloader/releases/latest/), and extract it.

Open up the folder and open up a terminal, assuming you're a Windows user you can type cmd into folder path, and it should open a cmd in the current directory, or you can hold the shift key and right click, and you should have the option to open PowerShell.

Once a terminal is open, install the needed requirements with the command:
```sh
pip install -r requirements.txt
```

To edit the config, go into the src folder and find the file 'config.json' and you can adjust your config from there, if you're modifying the download directory option, if the path you put in there contains any backslashes make sure they are doubled up!

```
From: C:\Location\To\Download\To
To: C:\\Location\\To\\Download\\To
```

After installing the needed requirements, use the following command to start the program:
```sh
python src/main.py
```

Once the program is running, it should open up an image of a captcha, enter the characters into the program.
If entered correctly, it will say "Session with captcha successfully created".

After that, you can start downloading stuff!
To download stuff from The Sims Resource, simply copy the URL of the item you want to download, and it will start downloading.

**Comment by annasayswho** [comment]
Thank you, it worked!

**Comment by KristinaShymanska** [comment]
![image](https://github.com/Xientraa/The-Sims-Resource-Downloader/assets/90703917/3a4de793-6336-4909-8886-738b15f76b83)
Hello, can u please tell what to do with error? thanks

**Comment by Xientraa** [comment]
Apologies for taking so long to respond! This is not unwarranted at all, I am thankful for any feedback, especially when it helps less tech-savvy users use the tool. I have been working on a full Wiki guide, though have got a bit busy and still have to finish it. I also use uBlock Origin, and I never realized just how many ads there were, until I was testing it out on a Windows VM. I absolutely despise their premium adverts being forced down our throats every chance they get.

**Comment by aubryssme** [comment]
Its saying 
C:\Users\chadw>python src/main.py
python: can't open file 'C:\\Users\\chadw\\src\\main.py': [Errno 2] No such file or directory
and its not working. Please help.

**Comment by OverjoyedH** [comment]
I really dont understand how to use it, any help?

**Comment by 0xzc11** [comment]
I have the same problem as aubryss.

**Comment by Xientraa** [comment]
You need to manually change the directory, please check out this issue: https://github.com/Xientraa/The-Sims-Resource-Downloader/issues/13

**Comment by sadsmallcoconut** [comment]
I started using ths recently without any problems, but I now keep getting [ERROR] Invalid captcha code entered, please make sure the code is correct, even when the captcha is the same

**Comment by Xientraa** [comment]
Please check out Issue #16.
Also going to be locking this issue, if anyone has problems using this tool, please check for other issues similar to yours, otherwise create a new issue.
